### ISSUE TITLE
NullReferenceException in MaterialParser

### ISSUE THREAD

**Issue by ms440** [tgjones/meshellator#2]
According to OBJ spec, 

```
usemtl material-ref 
```

operator could be found before any group is created. The following test is failing:

```
# start test file
mtllib ./mylib.mtl
usemtl red
# end test file
```

---

**To fix this issue I would propose the following change in MaterialParser.IncorporateResults():**

```
    public override void IncorporateResults(WavefrontObject wavefrontObject) {
        if (!wavefrontObject.Materials.ContainsKey(_materialName))
            return;

        Material newMaterial = wavefrontObject.Materials[_materialName];

        // Fix: CurrentGroup could be null...
        if ( wavefrontObject.CurrentGroup == null ) {
            wavefrontObject.CurrentGroup = new Group("default");
        }
        wavefrontObject.CurrentGroup.Material = newMaterial;
    }
```

Note that OBJ spec is using "default" as a group name in these cases (**not "Default created by loader"**)

**Comment by tgjones** [comment]
Incorporated Michael&#39;s suggestion for allowing material to be used before any group is created. Closed by f264e7859d227bb76459fddf7806c5d02bcf06a0.
Also used proper default group name.
