### ISSUE TITLE
Errors on opening my mesh

### ISSUE THREAD

**Issue by ekolis** [tgjones/meshellator#6]
I have an OBJ mesh (I'd like to attach it to this issue, but I don't know how) that crashes Meshellator when I attempt to load it. First I got an "dictionary key not found" error in the MTL loader; I figured out that was because I had spaces in some of my material names, so I removed the spaces from both the MTL file and the references to the materials in the OBJ file. However even after doing so I get an error that I can't figure out. It's just an "index out of range" error, and it's in the OBJ loader itself, so I'm not sure what's wrong.

edit: Since I can't seem to attach files, I'll link to my mesh here: http://edkolis.exofire.net/hull-segment-1.7z

**Comment by ekolis** [comment]
I downloaded the source code so I can fix these bugs and make a pull request. (The "index out of range" error was Meshellator trying to load texture coordinates for a model that has none!) Now I'm getting an "unsupported operation" - apparently something somewhere is asking for quads, but it only supports triangles?

**Comment by tgjones** [comment]
Somehow this issue slipped off my radar, sorry! I've just fixed #7, which seems to be the same issue as the one you mentioned with texture coordinates. As for quads, you're right, Meshellator's OBJ importer only supports triangles.
